#Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/ApterKingRepo/Specs.git'
platform :ios, '9.0'

target 'VerifyProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VerifyProject

  target 'VerifyProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VerifyProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
